services:
  - type: web
    name: callcast
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
